version: '3'

services:
  site:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started
      mysql: 
        condition: service_healthy
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "homestead", "-psecret" ]
      interval: 5s
      timeout: 10s
      retries: 30
      start_period: 30s
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: homestead
      PMA_PASSWORD: secret
    volumes:
      - ./dockerfiles/php/upload.ini:/usr/local/etc/php/php.ini
    ports:
      - "8888:80"

  php:
    image: issaadi/photogallery-php8.1.5:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"

  composer:
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
  npm:
    image: node:14.8
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
  artisan:
    image: issaadi/photogallery-artisan:latest
    volumes:
      - ./src:/var/www/html
    depends_on:
      mysql: 
        condition: service_healthy
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
